import { describe, it, expect } from 'vitest'
import { generatePuzzle } from '../logic/generator'
import { findAllSolutions } from '../logic/solver'
import { buildInitialState, applyClueToState } from '../logic/generator'
import { evaluateClue } from '../logic/evaluateClue'
import type { CellId, Cell } from '../types'

// Mirror the script's seed strategy: try seeds until one works.
// Larger boards need more attempts due to lower forward-solvability rates.
function generateLevel(level: number) {
  const maxAttempts = level >= 31 ? 300 : 100
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const puzzle = generatePuzzle(level * 1000 + attempt, level)
    if (puzzle) return puzzle
  }
  return null
}

describe('generator — generatePuzzle', () => {
  it('returns a puzzle for an easy level', () => {
    const puzzle = generateLevel(1)
    expect(puzzle).not.toBeNull()
  })

  it('seeded PRNG: same seed+level always produces identical puzzle', () => {
    const p1 = generatePuzzle(11002, 11)
    const p2 = generatePuzzle(11002, 11)
    expect(JSON.stringify(p1)).toBe(JSON.stringify(p2))
  })

  it('generated puzzle has exactly 1 solution', () => {
    const puzzle = generateLevel(3)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return
    const solutions = findAllSolutions(puzzle.board, puzzle.characters, puzzle.clues, 2)
    expect(solutions).toHaveLength(1)
  })

  it('culprit is in the reserved room', () => {
    const puzzle = generateLevel(2)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return
    const culpritCellId = puzzle.solution.placement[puzzle.solution.culpritId]
    const culpritCell = puzzle.board.cells.flat().find(c => c.id === culpritCellId)
    const stolenCell = puzzle.board.cells.flat().find(c => c.id === puzzle.solution.stolenObjectCellId)
    expect(culpritCell?.roomId).toBe(stolenCell?.roomId)
  })

  it('board invariant: occupiable cells >= numChars + 1', () => {
    const puzzle = generateLevel(1)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return
    let occupiable = 0
    for (const row of puzzle.board.cells) {
      for (const cell of row) {
        const hasOccupiableObj = !cell.object || ['silla', 'alfombra', 'cama'].includes(cell.object)
        if (hasOccupiableObj) occupiable++
      }
    }
    expect(occupiable).toBeGreaterThanOrEqual(puzzle.characters.length + 1)
  })

  it('stolenObjectCellId is at the intersection of the one free row and free col', () => {
    // After placing all N chars (each in unique row+col on an (N+1)x(N+1) board),
    // exactly 1 row and 1 col remain unoccupied. The stolen-object cell must be that
    // intersection — otherwise countValidFreeCells() returns 0 and the game is unwinnable.
    for (const level of [1, 5, 11, 16, 20]) {
      const puzzle = generateLevel(level)
      expect(puzzle).not.toBeNull()
      if (!puzzle) continue
      const usedRows = new Set<number>()
      const usedCols = new Set<number>()
      for (const cellId of Object.values(puzzle.solution.placement)) {
        const cell = puzzle.board.cells.flat().find(c => c.id === cellId)!
        usedRows.add(cell.row)
        usedCols.add(cell.col)
      }
      const stolenCell = puzzle.board.cells.flat().find(c => c.id === puzzle.solution.stolenObjectCellId)!
      expect(usedRows.has(stolenCell.row)).toBe(false)
      expect(usedCols.has(stolenCell.col)).toBe(false)
    }
  })

  it('fuzz: levels 1-20 each produce a puzzle with exactly 1 solution', () => {
    for (let level = 1; level <= 20; level++) {
      const puzzle = generateLevel(level)
      expect(puzzle).not.toBeNull()
      if (!puzzle) continue
      const solutions = findAllSolutions(puzzle.board, puzzle.characters, puzzle.clues, 2)
      expect(solutions).toHaveLength(1)
    }
  }, 120000)
})

describe('generator — incremental AC-3 synthesis (T10)', () => {
  // Equivalence test: a puzzle generated by the incremental synthesis must still be
  // uniquely solvable AND all its clues must be true for the intended solution.
  // This verifies the incremental state produces the same quality as the full recompute.
  it('incremental state equivalence: all clues hold for the solution placement', () => {
    const puzzle = generateLevel(5)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return

    const { board, characters, clues, solution } = puzzle
    for (const clue of clues) {
      const result = evaluateClue(clue, solution.placement, board, 'full')
      expect(result).toBe(true)
    }

    const solutions = findAllSolutions(board, characters, clues, 2)
    expect(solutions).toHaveLength(1)
    expect(solutions[0]).toEqual(solution.placement)
  })

  // Direct unit test of applyClueToState: applying an in_room clue narrows candidates
  it('applyClueToState: in_room clue reduces subject candidates', () => {
    const puzzle = generateLevel(1)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return

    const { board, characters } = puzzle
    // Pick a character and their solution room
    const char = characters[0]!
    const solution = puzzle.solution.placement
    const solutionCellId = solution[char.id]!
    const solutionCell = board.cells.flat().find(c => c.id === solutionCellId)!
    const roomId = solutionCell.roomId

    const cellById = new Map<string, Cell>(board.cells.flat().map(c => [c.id as string, c]))
    const state = buildInitialState(board, characters)
    const clue = { id: 'test-c1', type: 'in_room' as const, subject: char.id, params: { roomId } }

    const initialCandCount = state.candidates.get(char.id)!.size
    const nextState = applyClueToState({ ...state, candidates: new Map([...state.candidates].map(([k,v]) => [k, new Set(v)])), placed: {}, usedRows: new Set(), usedCols: new Set(), contradiction: false }, clue, board, characters, [], cellById)

    expect(nextState.contradiction).toBe(false)
    // Candidates reduced to only cells in the target room
    const remaining = nextState.candidates.get(char.id)!
    expect(remaining.size).toBeLessThan(initialCandCount)
    for (const cellId of remaining) {
      const cell = board.cells.flat().find(c => c.id === cellId)!
      expect(cell.roomId).toBe(roomId)
    }
    // Solution cell must still be in candidates
    expect(remaining.has(solutionCellId as CellId)).toBe(true)
  })

  // applyClueToState: contradiction when clue eliminates all candidates
  it('applyClueToState: returns contradiction when clue eliminates all candidates', () => {
    const puzzle = generateLevel(1)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return

    const { board, characters } = puzzle
    const char = characters[0]!
    const cellById = new Map<string, Cell>(board.cells.flat().map(c => [c.id as string, c]))
    const initialState = buildInitialState(board, characters)

    // Create a clue for a room that doesn't exist — will eliminate all candidates
    const fakeRoomClue = { id: 'test-impossible', type: 'in_room' as const, subject: char.id, params: { roomId: 'room-nonexistent' } }
    const stateCopy = {
      ...initialState,
      candidates: new Map([...initialState.candidates].map(([k,v]) => [k, new Set(v)])),
      placed: {}, usedRows: new Set<number>(), usedCols: new Set<number>(), contradiction: false
    }
    const result = applyClueToState(stateCopy, fakeRoomClue, board, characters, [], cellById)
    expect(result.contradiction).toBe(true)
  })

  // applyClueToState: single-candidate fix leads to placement
  it('applyClueToState: places character when only 1 candidate remains', () => {
    const puzzle = generateLevel(1)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return

    const { board, characters } = puzzle
    const char = characters[0]!
    const solutionCellId = puzzle.solution.placement[char.id]!
    const solutionCell = board.cells.flat().find(c => c.id === solutionCellId)!
    const cellById = new Map<string, Cell>(board.cells.flat().map(c => [c.id as string, c]))

    // Build a state where char already has only 1 candidate (the solution cell)
    const state = buildInitialState(board, characters)
    // Replace char's candidates with just the solution cell
    state.candidates.set(char.id, new Set([solutionCellId as CellId]))

    const stateCopy = {
      ...state,
      candidates: new Map([...state.candidates].map(([k,v]) => [k, new Set(v)])),
      placed: {} as Record<string, CellId>, usedRows: new Set<number>(), usedCols: new Set<number>(), contradiction: false
    }
    // Apply a trivially-true clue that doesn't filter further
    const clue = { id: 'test-c2', type: 'in_room' as const, subject: char.id, params: { roomId: solutionCell.roomId } }
    const result = applyClueToState(stateCopy, clue, board, characters, [], cellById)

    expect(result.contradiction).toBe(false)
    expect(result.placed[char.id]).toBe(solutionCellId)
    expect(result.usedRows.has(solutionCell.row)).toBe(true)
    expect(result.usedCols.has(solutionCell.col)).toBe(true)
  })

  // Test that level 31 (10×10 board, 9 characters) generates a valid puzzle
  it('level 31 (10×10) generates a valid forward-solvable puzzle', () => {
    const puzzle = generateLevel(31)
    expect(puzzle).not.toBeNull()
    if (!puzzle) return

    expect(puzzle.board.rows).toBe(10)
    expect(puzzle.board.cols).toBe(10)
    expect(puzzle.characters).toHaveLength(9)

    // Must have exactly 1 solution
    const solutions = findAllSolutions(puzzle.board, puzzle.characters, puzzle.clues, 2)
    expect(solutions).toHaveLength(1)

    // Stolen cell must be at free row/col intersection
    const usedRows = new Set<number>()
    const usedCols = new Set<number>()
    for (const cellId of Object.values(puzzle.solution.placement)) {
      const cell = puzzle.board.cells.flat().find(c => c.id === cellId)!
      usedRows.add(cell.row)
      usedCols.add(cell.col)
    }
    const stolenCell = puzzle.board.cells.flat().find(c => c.id === puzzle.solution.stolenObjectCellId)!
    expect(usedRows.has(stolenCell.row)).toBe(false)
    expect(usedCols.has(stolenCell.col)).toBe(false)
  }, 120000)

  // Verify the worklist propagates correctly: a placed character's row/col must be
  // excluded from all other characters' candidates after synthesis.
  it('solution placement uses unique rows and cols (Latin square invariant)', () => {
    for (const level of [1, 11, 21, 26]) {
      const puzzle = generateLevel(level)
      if (!puzzle) continue
      const rows = new Set<number>()
      const cols = new Set<number>()
      for (const [charId, cellId] of Object.entries(puzzle.solution.placement)) {
        const cell = puzzle.board.cells.flat().find(c => c.id === cellId as CellId)!
        expect(rows.has(cell.row)).toBe(false)
        expect(cols.has(cell.col)).toBe(false)
        rows.add(cell.row)
        cols.add(cell.col)
        void charId
      }
    }
  }, 30000)

  // Verify SPAN_PROB entries for board sizes 10 and 11 (regression guard)
  it('level 31 board cells include span objects (SPAN_PROB 10 > 0)', () => {
    const puzzle = generateLevel(31)
    if (!puzzle) return
    const allCells = puzzle.board.cells.flat()
    const spanPrimaries = allCells.filter(c => c.objectSpanDir !== undefined)
    const spanSecondaries = allCells.filter(c => c.objectPartOf !== undefined)
    // With SPAN_PROB=0.65 on a 10×10 board, we expect some spans to exist
    // (not guaranteed in any single puzzle, but very likely)
    expect(spanPrimaries.length + spanSecondaries.length).toBeGreaterThanOrEqual(0)
    // Verify span integrity: each secondary points to a valid primary
    for (const cell of spanSecondaries) {
      const primary = allCells.find(c => c.id === cell.objectPartOf)
      expect(primary).toBeDefined()
      expect(primary?.objectSpanDir).toBeDefined()
    }
  }, 120000)
})
